# Generated by Django 3.1.1 on 2020-09-27 15:03

import connect4.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect4', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='count',
            new_name='turn',
        ),
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.JSONField(default=connect4.models.board_design),
        ),
    ]
