# Generated by Django 3.1.1 on 2020-09-27 16:03

import connect4.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect4', '0002_auto_20200927_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.IntegerField()),
                ('player', models.IntegerField(default=0)),
                ('old_state', models.JSONField(default=connect4.models.board_design)),
                ('new_state', models.JSONField(default=connect4.models.board_design)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
